from nta_backend.api.routers import (
    auth,
    benchmark_leaderboards,
    benchmarks,
    datasets,
    evaluation_catalog_v2,
    evaluation_runs_v2,
    eval_jobs,
    health,
    lake,
    model_providers,
    models,
    projects,
    streams,
    uploads,
    ws,
)

__all__ = [
    "auth",
    "benchmark_leaderboards",
    "benchmarks",
    "datasets",
    "evaluation_catalog_v2",
    "evaluation_runs_v2",
    "eval_jobs",
    "health",
    "lake",
    "model_providers",
    "models",
    "projects",
    "streams",
    "uploads",
    "ws",
]
