"""init schema

Revision ID: 6b98732bbb08
Revises: 
Create Date: 2026-03-21 01:07:59.561653
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b98732bbb08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('code', name=op.f('uq_projects_code'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_api_keys_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_project_id'), 'api_keys', ['project_id'], unique=False)
    op.create_table('datasets',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purpose', sa.String(length=64), nullable=True),
    sa.Column('format', sa.String(length=32), nullable=True),
    sa.Column('latest_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_datasets_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    op.create_index(op.f('ix_datasets_project_id'), 'datasets', ['project_id'], unique=False)
    op.create_table('job_logs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=24), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logged_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_job_logs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_logs'))
    )
    op.create_index(op.f('ix_job_logs_job_id'), 'job_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_logs_project_id'), 'job_logs', ['project_id'], unique=False)
    op.create_table('models',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('base_model', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_models_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index(op.f('ix_models_project_id'), 'models', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_members'))
    )
    op.create_index('ix_project_members_project_user', 'project_members', ['project_id', 'user_id'], unique=True)
    op.create_table('quota_rules',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_code', sa.String(length=120), nullable=False),
    sa.Column('account_quota', sa.BigInteger(), nullable=True),
    sa.Column('shared_ratio', sa.Float(), nullable=True),
    sa.Column('exclusive_ratio', sa.Float(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_quota_rules_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quota_rules'))
    )
    op.create_index(op.f('ix_quota_rules_project_id'), 'quota_rules', ['project_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('model_code', sa.String(length=120), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('request_count', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_usage_events_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_events'))
    )
    op.create_index(op.f('ix_usage_events_project_id'), 'usage_events', ['project_id'], unique=False)
    op.create_table('vpc_bindings',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('vpc_id', sa.String(length=120), nullable=False),
    sa.Column('subnet_id', sa.String(length=120), nullable=True),
    sa.Column('private_link_service_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_vpc_bindings_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vpc_bindings'))
    )
    op.create_index(op.f('ix_vpc_bindings_project_id'), 'vpc_bindings', ['project_id'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('object_key', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('record_count', sa.BigInteger(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dataset_versions_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_versions'))
    )
    op.create_index(op.f('ix_dataset_versions_dataset_id'), 'dataset_versions', ['dataset_id'], unique=False)
    op.create_index('ix_dataset_versions_dataset_version', 'dataset_versions', ['dataset_id', 'version'], unique=True)
    op.create_table('endpoints',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('endpoint_type', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('purchase_type', sa.String(length=64), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_endpoints_model_id_models')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_endpoints_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_endpoints'))
    )
    op.create_index(op.f('ix_endpoints_project_id'), 'endpoints', ['project_id'], unique=False)
    op.create_table('batch_jobs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('endpoint_id', sa.UUID(), nullable=True),
    sa.Column('input_object_key', sa.Text(), nullable=True),
    sa.Column('output_object_key', sa.Text(), nullable=True),
    sa.Column('temporal_workflow_id', sa.String(length=128), nullable=True),
    sa.Column('progress_total', sa.BigInteger(), nullable=True),
    sa.Column('progress_done', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name=op.f('fk_batch_jobs_endpoint_id_endpoints')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_batch_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_jobs'))
    )
    op.create_index(op.f('ix_batch_jobs_project_id'), 'batch_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_batch_jobs_temporal_workflow_id'), 'batch_jobs', ['temporal_workflow_id'], unique=False)
    op.create_table('dataset_files',
    sa.Column('dataset_version_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('fk_dataset_files_dataset_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_files'))
    )
    op.create_index(op.f('ix_dataset_files_dataset_version_id'), 'dataset_files', ['dataset_version_id'], unique=False)
    op.create_table('eval_jobs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_source', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('inference_mode', sa.String(length=64), nullable=True),
    sa.Column('eval_method', sa.String(length=64), nullable=True),
    sa.Column('criteria_text', sa.Text(), nullable=True),
    sa.Column('dataset_version_id', sa.UUID(), nullable=True),
    sa.Column('temporal_workflow_id', sa.String(length=128), nullable=True),
    sa.Column('batch_job_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('fk_eval_jobs_dataset_version_id_dataset_versions')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_eval_jobs_model_id_models')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_eval_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_jobs'))
    )
    op.create_index(op.f('ix_eval_jobs_project_id'), 'eval_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_eval_jobs_temporal_workflow_id'), 'eval_jobs', ['temporal_workflow_id'], unique=False)
    op.create_table('security_events',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=True),
    sa.Column('risk_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name=op.f('fk_security_events_endpoint_id_endpoints')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_security_events_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    op.create_index(op.f('ix_security_events_project_id'), 'security_events', ['project_id'], unique=False)
    op.create_table('usage_daily_agg',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('model_code', sa.String(length=120), nullable=True),
    sa.Column('endpoint_id', sa.UUID(), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('request_count', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name=op.f('fk_usage_daily_agg_endpoint_id_endpoints')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_usage_daily_agg_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_daily_agg'))
    )
    op.create_index(op.f('ix_usage_daily_agg_project_id'), 'usage_daily_agg', ['project_id'], unique=False)
    op.create_index('ix_usage_daily_project_date_model', 'usage_daily_agg', ['project_id', 'date', 'model_code'], unique=False)
    op.create_table('eval_job_metrics',
    sa.Column('eval_job_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=120), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=32), nullable=True),
    sa.Column('extra_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eval_job_id'], ['eval_jobs.id'], name=op.f('fk_eval_job_metrics_eval_job_id_eval_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_job_metrics'))
    )
    op.create_index(op.f('ix_eval_job_metrics_eval_job_id'), 'eval_job_metrics', ['eval_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eval_job_metrics_eval_job_id'), table_name='eval_job_metrics')
    op.drop_table('eval_job_metrics')
    op.drop_index('ix_usage_daily_project_date_model', table_name='usage_daily_agg')
    op.drop_index(op.f('ix_usage_daily_agg_project_id'), table_name='usage_daily_agg')
    op.drop_table('usage_daily_agg')
    op.drop_index(op.f('ix_security_events_project_id'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_eval_jobs_temporal_workflow_id'), table_name='eval_jobs')
    op.drop_index(op.f('ix_eval_jobs_project_id'), table_name='eval_jobs')
    op.drop_table('eval_jobs')
    op.drop_index(op.f('ix_dataset_files_dataset_version_id'), table_name='dataset_files')
    op.drop_table('dataset_files')
    op.drop_index(op.f('ix_batch_jobs_temporal_workflow_id'), table_name='batch_jobs')
    op.drop_index(op.f('ix_batch_jobs_project_id'), table_name='batch_jobs')
    op.drop_table('batch_jobs')
    op.drop_index(op.f('ix_endpoints_project_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index('ix_dataset_versions_dataset_version', table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_dataset_id'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_vpc_bindings_project_id'), table_name='vpc_bindings')
    op.drop_table('vpc_bindings')
    op.drop_index(op.f('ix_usage_events_project_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_quota_rules_project_id'), table_name='quota_rules')
    op.drop_table('quota_rules')
    op.drop_index('ix_project_members_project_user', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_models_project_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_job_logs_project_id'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_job_id'), table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index(op.f('ix_datasets_project_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_api_keys_project_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###

